spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/survey?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: LIZHONGJIE199608
  redis:
    host: localhost
    port: 6379
    timeout: 20000
    pool:
      max-idle: 0
      min-idle: 1
      max-active: 8
      max-wait: -1
  application:
    name: spring-boot-redis

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: false

  jackson:
    date-format: yyyy-MM-hh HH:mm:ss
    time-zone: GMT+8


server:
  tomcat:
    uri-encoding: utf-8
  port: 8888

security:
  basic:
    enabled: true
  user:
    name: admin
    password: 123